### ISSUE TITLE
Why not use a vector to store children?

### ISSUE THREAD

**Issue by djn658** [Davis-Computer-Science/ecs36c-hw3#1]
This is a weird implementation of N-Ary Tree, may I know why you chose to use `**children` instead of a vector to store all children, which is the probably the most intuitive and effective way to iterate through the tree? As a matter of fact how do you visit **all** children of a`TreeNode` when you only has a pointer to pointer that points to another single TreeNode? Could you please provide some insights/hints? Much appreciated!

**Comment by kxylu** [comment]
Please ask this on canvas.
